# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservice2.proto\"#\n\x0fReadFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"(\n\x10ReadFileResponse\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x32<\n\tServices2\x12/\n\x08ReadFile\x12\x10.ReadFileRequest\x1a\x11.ReadFileResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _READFILEREQUEST._serialized_start=18
  _READFILEREQUEST._serialized_end=53
  _READFILERESPONSE._serialized_start=55
  _READFILERESPONSE._serialized_end=95
  _SERVICES2._serialized_start=97
  _SERVICES2._serialized_end=157
# @@protoc_insertion_point(module_scope)
