# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservice1.proto\"(\n\nSumRequest\x12\x0c\n\x04\x61rg1\x18\x01 \x01(\x05\x12\x0c\n\x04\x61rg2\x18\x02 \x01(\x05\"\x1d\n\x0bSumResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"(\n\nSubRequest\x12\x0c\n\x04\x61rg1\x18\x01 \x01(\x05\x12\x0c\n\x04\x61rg2\x18\x02 \x01(\x05\"\x1d\n\x0bSubResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"(\n\nMulRequest\x12\x0c\n\x04\x61rg1\x18\x01 \x01(\x05\x12\x0c\n\x04\x61rg2\x18\x02 \x01(\x05\"\x1d\n\x0bMulResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\"(\n\nDivRequest\x12\x0c\n\x04\x61rg1\x18\x01 \x01(\x05\x12\x0c\n\x04\x61rg2\x18\x02 \x01(\x05\"\x1d\n\x0b\x44ivResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\x32\x93\x01\n\tServices1\x12 \n\x03Sum\x12\x0b.SumRequest\x1a\x0c.SumResponse\x12 \n\x03Sub\x12\x0b.SubRequest\x1a\x0c.SubResponse\x12 \n\x03\x44iv\x12\x0b.DivRequest\x1a\x0c.DivResponse\x12 \n\x03Mul\x12\x0b.MulRequest\x1a\x0c.MulResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUMREQUEST._serialized_start=18
  _SUMREQUEST._serialized_end=58
  _SUMRESPONSE._serialized_start=60
  _SUMRESPONSE._serialized_end=89
  _SUBREQUEST._serialized_start=91
  _SUBREQUEST._serialized_end=131
  _SUBRESPONSE._serialized_start=133
  _SUBRESPONSE._serialized_end=162
  _MULREQUEST._serialized_start=164
  _MULREQUEST._serialized_end=204
  _MULRESPONSE._serialized_start=206
  _MULRESPONSE._serialized_end=235
  _DIVREQUEST._serialized_start=237
  _DIVREQUEST._serialized_end=277
  _DIVRESPONSE._serialized_start=279
  _DIVRESPONSE._serialized_end=308
  _SERVICES1._serialized_start=311
  _SERVICES1._serialized_end=458
# @@protoc_insertion_point(module_scope)
